# Generated by Django 3.1 on 2020-09-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbboard', '0002_auto_20200915_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Todo'), (1, 'In Progress'), (2, 'Done')], default=0),
        ),
    ]
